# Generated by Django 4.0 on 2021-12-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tomeet'),
    ]

    operations = [
        migrations.CreateModel(
            name='goal_for_month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=20)),
                ('month', models.DateField()),
                ('difficulty', models.CharField(max_length=10)),
                ('reason_for_goal', models.TextField(max_length=20)),
            ],
        ),
    ]
