# Generated by Django 4.0 on 2021-12-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_goal_for_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal_for_month',
            name='reason_for_goal',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tomeet',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
    ]
