# Generated by Django 4.0 on 2021-12-18 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_goal_for_month_reason_for_goal_alter_todo_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tomeet',
            old_name='persone',
            new_name='person',
        ),
    ]
