# Generated by Django 4.0 on 2021-12-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_tomeet_date_of_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomeet',
            name='date_of_meeting',
            field=models.DateField(),
        ),
    ]
