# Generated by Django 4.0 on 2022-01-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_habits'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal_for_month',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
