# Generated by Django 4.0 on 2022-01-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_goal_for_month_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal_for_month',
            name='difficulty',
            field=models.CharField(default='easy', max_length=10),
        ),
    ]
