# Generated by Django 4.0 on 2022-01-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_goal_for_month_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal_for_month',
            name='difficulty',
            field=models.CharField(default='easy', max_length=10),
        ),
    ]
